name: admin_ai_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'  # Updated to match installed SDK version

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  page_transition: ^2.1.0
  cupertino_icons: ^1.0.2
  universal_html: ^2.2.4
  
  # Core Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_auth_web: ^5.8.5
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_storage_web: ^3.6.17
  shared_preferences: ^2.2.2
  
  # Required for web
  js: ^0.7.1
  uuid: ^4.5.1
  flutter_colorpicker: 1.1.0
  cached_network_image: ^3.4.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
