// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiZs7P-f0J57zJ_5c8pEY_dnmwJcFISxg',
    appId: '1:1094554838824:web:8af716026d029517b8521d',
    messagingSenderId: '1094554838824',
    projectId: 'store-7ff06',
    authDomain: 'store-7ff06.firebaseapp.com',
    storageBucket: 'store-7ff06.appspot.com',
    measurementId: 'G-LQYW9VWJQ8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTkyCLnW_F3MwtLi88yaGYteXMbGImrFA',
    appId: '1:1094554838824:ios:01fc8bed08fb2f5ab8521d',
    messagingSenderId: '1094554838824',
    projectId: 'store-7ff06',
    storageBucket: 'store-7ff06.appspot.com',
    androidClientId: '1094554838824-aac4mc75maff9pjmvtbu4b342e52nqvr.apps.googleusercontent.com',
    iosClientId: '1094554838824-umbbk7533vhu07jtnidts5551nlb4m2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminAiWeb',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTkyCLnW_F3MwtLi88yaGYteXMbGImrFA',
    appId: '1:1094554838824:ios:01fc8bed08fb2f5ab8521d',
    messagingSenderId: '1094554838824',
    projectId: 'store-7ff06',
    storageBucket: 'store-7ff06.appspot.com',
    androidClientId: '1094554838824-aac4mc75maff9pjmvtbu4b342e52nqvr.apps.googleusercontent.com',
    iosClientId: '1094554838824-umbbk7533vhu07jtnidts5551nlb4m2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminAiWeb',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh2Kh-7ZFLguLZnz1YGWhyzjdebiXOoWw',
    appId: '1:1094554838824:android:9389f160c77b17e5b8521d',
    messagingSenderId: '1094554838824',
    projectId: 'store-7ff06',
    storageBucket: 'store-7ff06.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiZs7P-f0J57zJ_5c8pEY_dnmwJcFISxg',
    appId: '1:1094554838824:web:14df0185418294f4b8521d',
    messagingSenderId: '1094554838824',
    projectId: 'store-7ff06',
    authDomain: 'store-7ff06.firebaseapp.com',
    storageBucket: 'store-7ff06.appspot.com',
    measurementId: 'G-G7F9WZTE6T',
  );

}